Blog/urls.py
from django.urls import path
from Blog import views




urlpatterns = [
    path('', views.blog, name='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria'),
]

Carro/urls.py
from django.urls import path
from .import views

app_name='carro'



urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

Proyecto_WEB/urls.py
from django.contrib import admin
from django.urls import path
from ProyectoWebApp.views import home
from Servicios.views import services
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('services/', include('Servicios.urls')),
    path('blog/', include('Blog.urls')),
    path('contact/', include('Contacto.urls')),
    path('shop/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('autenticacion/', include('Autenticacion.urls')),
    path('pedidos/', include('Pedidos.urls')),
]

Tienda/urls.py
from django.urls import path
from Tienda import views




urlpatterns = [
    path('', views.shop, name='Shop'),
]

Carro/models.py
from django.db import models

# Create your models here.

Tienda/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class CategoriaProducto(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True) #Para agregar la fecha automaticamente auto_now_add
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Categoria Producto'
        verbose_name_plural='Categorias Productos'

    def __str__(self):
        
        return self.nombre



class Producto(models.Model):
    titulo=models.CharField(max_length=50)
    precio=models.FloatField()
    descripcion=models.CharField(max_length=250)
    imagen=models.ImageField(upload_to='Tienda', null=True, blank=True)
    autor=models.ForeignKey(User, on_delete=models.CASCADE)
    categorias=models.ManyToManyField(CategoriaProducto)
    stock=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True) #Para agregar la fecha automaticamente auto_now_add
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'

    def __str__(self):
        
        return self.titulo

Carro/views.py
from django.shortcuts import render
from .carro import Carro
from Tienda.models import Producto
from django.shortcuts import redirect
# Create your views here.


def agregar_producto(request, producto_id):
    
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Shop")




def eliminar_producto(request, producto_id):
    
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Shop")




def restar_producto(request, producto_id):
    
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Shop")




def limpiar_carro(request):
    
    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Shop")

Tienda/views.py
from django.shortcuts import render

from .models import Producto

# Create your views here.

def shop(request):
    productos=Producto.objects.all()
    return render(request,'Tienda/shop.html', {'productos':productos})

Tienda/templates/carro/widget.html
<table class="table table-dark table-responsive table-bordered" style="color: white;">

    <thead>

        <tr>

            <th colspan="3" class="text-center">

                Carro compras

            </th>


        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>

        </tr>


    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>
                        {{value.precio}} €

                    </td>



                </tr>


            {% endfor %}
        {% else %}
            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>

            </tr>


        {% endif %}

    </tbody>


    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{importe_total_carro}} €
            </td>

        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" class="text-center">
                <a href="../pedidos" class="btn btn-success">Realizar pedido</a>
            </td>
        </tr>
        {% endif %}
        
        <tr>
            <td colspan="3" class="text-center">
                {% if messages %}
                    {% for message in messages %}
                        <a {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</a>
                    {% endfor %}
                {% endif %}        
            </td>
        </tr>
        
    </tfoot>


</table>